# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Angular Build && Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    environment: Prod
    strategy:
      matrix:
        node-version: [19.x]
    steps:
    - uses: actions/checkout@v3

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: (Get-Content src\environments\environment.prod.ts) -replace 'SERVER_URL', '${{ secrets.SERVER_URL }}' | Out-File -encoding utf8 src\environments\environment.prod.ts
    - run: npm i
    - run: ng build --configuration production --base-href /europium-frontend/ --aot
   # - run: cp -r ./dist/angular-deploy-github-self-host/* /usr/share/nginx/html
